version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'True'
    container_name: redis
    hostname: redis-12367.c305.ap-south-1-1.ec2.cloud.redislabs.com
    ports:
      - '12367:12367'
    networks:
      - backend
    env_file:
      - .env
    restart: unless-stopped

networks:
  backend:
    driver: 'bridge'

volumes:
  postgres:
  pgadmin:
  redis: