"""empty message

Revision ID: b810aaf8b0a1
Revises: fe1e1f42ea3a
Create Date: 2022-11-13 23:16:34.641153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b810aaf8b0a1'
down_revision = 'fe1e1f42ea3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
