"""empty message

Revision ID: fe1e1f42ea3a
Revises:
Create Date: 2022-06-10 15:22:13.142783

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b810aaf8b0a1"
down_revision = "fe1e1f42ea3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
